#pragma once

#define ACCEPTABLE_MAP_KEY_TYPES M_T_INT | M_T_STRING
#define ACCEPTABLE_MAP_VALUE_TYPES M_T_STRING | M_T_INT | M_T_BOOL | M_T_FLOAT | M_T_FN

#define ACCEPTABLE_ARRAY_KEY_TYPES M_T_INT

#define ACCEPTABLE_ASSIGNMENT_LEFT_SIDE_EXPRESSION_KINDS M_EK_ID | M_EK_INDEX

#define ACCEPTABLE_FOR_KEY_EXPRESSION_KINDS M_EK_ID
#define ACCEPTABLE_FOR_OF_TARGET_EXPRESSION_KINDS M_EK_ARRAY | M_EK_STRING | M_EK_MAP
#define ACCEPTABLE_FOR_OF_TARGET_VALUE_TYPES M_T_ARRAY | M_T_STRING | M_T_MAP
