#pragma once

#define ACCEPTABLE_MAP_KEY_TYPES M_T_INT | M_T_STRING
#define ACCEPTABLE_MAP_VALUE_TYPES M_T_STRING | M_T_INT | M_T_BOOL | M_T_FLOAT | M_T_FN

#define ACCEPTABLE_ARRAY_KEY_TYPES M_T_INT

#define ACCEPTABLE_ASSIGNMENT_LEFT_SIDE_EXPRESSION_KINDS M_EK_ID | M_EK_INDEX
